name: restaurants-api

on:
  push:
    branches: [master]
  pull_request:
   branches: 
   - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/Restaurants.API/Restaurants.API.csproj
      - name: Build
        run: dotnet build src/Restaurants.API/Restaurants.API.csproj --no-restore
      - name: Test
        run: dotnet test tests/Restaurants.Application.Tests/Restaurants.Application.Tests.csproj
